version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: encuestas
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - main
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - postgres
    networks:
      - main
  backend:
    container_name: encuestas_container_backend
    image: marioecheverria/encuesta-backend:v1
    mem_limit: 2048m
    mem_reservation: 512m
    cpus: 0.2
    restart: always
    ports:
      - "8080:8080"
    networks:
      - main
    depends_on:
      - postgres
  fronend:
    container_name: encuestas_container_frontend
    image: marioecheverria/encuesta-frontend:v1
    mem_limit: 2048m
    mem_reservation: 512m
    cpus: 0.2
    restart: always
    ports:
      - "80:80"
    networks:
      - main
    depends_on:
      - postgres

volumes:
  postgres:
networks:
  main:
